apiVersion: v1
kind: Service
metadata:
  name: backend-nodejs-service
  namespace: project-kubernetes-namespace
spec:
  selector:
    app: backend-nodejs
  type: ClusterIP
  ports:
    - port: 5000 # Backend service port
      targetPort: 5000 # Backend container port