apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-nextjs
  namespace: project-kubernetes-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-nextjs
  template:
    metadata:
      labels:
        app: frontend-nextjs
    spec:
      containers:
        - name: frontend-nextjs
          image: frontend-local
          ports:
            - containerPort: 3000
          env:
            - name: BACKEND_URL
              value: http://backend-nodejs-service:5000