apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-secret
  namespace: project-kubernetes-namespace
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA== # root
  MYSQL_DATABASE: bWFpbi1rdWJlcg== # main-kuber
  MYSQL_USER: dXNlcg== # user
  MYSQL_PASSWORD: cGFzc3dvcmQ= # password