apiVersion: v1
kind: Service
metadata:
  name: mysql-db-service
  namespace: project-kubernetes-namespace
spec:
  selector:
    app: mysql-db
  type: ClusterIP
  ports:
    - port: 3307 # MySQL service port
      targetPort: 3306 # MySQL container port