apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-db-volume
  namespace: project-kubernetes-namespace
spec:
  storageClassName: mysql-storage
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-db-pvc
  namespace: project-kubernetes-namespace
spec:
  storageClassName: mysql-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  namespace: project-kubernetes-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
        - name: mysql-db
          image: mysql-db-local
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: mysql-db-secret
          volumeMounts:
            - name: mysql-db-volume
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-db-volume
          persistentVolumeClaim:
            claimName: mysql-db-pvc
